# Generated by Django 4.0.6 on 2022-07-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_book_delete_product'),
        ('orders', '0003_salesorder_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='products',
            field=models.ManyToManyField(to='products.book'),
        ),
    ]
